export { Dashboard } from './Dashboard.icon';
export { Billing } from './Billing.icon';
export { Support } from './Support.icon';
export { Knowledge } from './Knowledge.icon';
export { Products } from './Products.icon';
export { Users } from './Users.icon';
export { Settings } from './Settings.icon';
export { TicketIcon } from './Ticket.icon';
export { WalletIcon } from './Wallet.icon';
