export const ArticlesData = [
    {
        id: 1,
        date: "1 Hour",
        avatar: "",
        name: "Paul Elliot",
        role: "CUSTOMER",
        content: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
    },
    {
        id: 2,
        date: "1 Hour",
        avatar: "",
        name: "Paul Elliot",
        role: "EMPLOYEE",
        content: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
    },
    {
        id: 3,
        date: "1 Hour",
        avatar: "/img/pauleliot2.png",
        name: "Paul Elliot",
        role: "CUSTOMER",
        content: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
    },
    {
        id: 4,
        date: "1 Hour",
        avatar: "",
        name: "Paul Elliot",
        role: "EMPLOYEE",
        content: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
    },
    {
        id: 5,
        date: "1 Hour",
        avatar: "",
        name: "Paul Elliot",
        role: "CUSTOMER",
        content: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
    },
    {
        id: 6,
        date: "1 Hour",
        avatar: "",
        name: "Paul Elliot",
        role: "EMPLOYEE",
        content: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
    },
    {
        id: 7,
        date: "1 Hour",
        avatar: "/img/pauleliot2.png",
        name: "Paul Elliot",
        role: "CUSTOMER",
        content: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
    },
    {
        id: 8,
        date: "1 Hour",
        avatar: "",
        name: "Paul Elliot",
        role: "EMPLOYEE",
        content: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
    },
    {
        id: 9,
        date: "1 Hour",
        avatar: "/img/pauleliot2.png",
        name: "Paul Elliot",
        role: "CUSTOMER",
        content: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
    },
    {
        id: 10,
        date: "1 Hour",
        avatar: "",
        name: "Paul Elliot",
        role: "EMPLOYEE",
        content: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
    }
]